---
title: "EDA user"
author: "Xiang XU"
date: "November 23, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(knitr,ggplot2, tidyverse, dplyr, ggraph, stringr, wordcloud, tidytext,tidyr,lubridate, widyr,jsonlite,sentimentr, benford.analysis)
```

##load prepared data
```{r}
#clear memory
rm(list = ls())



#read user_info data
user_info <- get(load("./Dataset/user_info.Rdata"));rm("df_user_info")
business_info <- get(load("./Dataset/business_info.Rdata"));rm("df_business_info")
checkin <- get(load("./Dataset/checkin.Rdata"));rm("df_checkin")
tip <- get(load("./Dataset/tip.Rdata"));rm("df_tip")
photo <- get(load("./Dataset/photos.Rdata"));rm("df_photo")

#rm(list = c("df_user_info","df_review","df_business_info","df_tip","df_photos","df_checkin"))
```

###add sentiment score to review data

```{r}
review <- get(load("./Dataset/review.Rdata"));rm("df_review")
dim(review)
#too large to process

#review sentiment
# review_sentence <- review %>%
#                     #group_by(review_id) %>%
#                     unnest_tokens(sentence, text, token = "sentences")
# review_sentiment <- review_sentence %>% 
#                     sentiment(na.omit(sentence)) %>%
#                     group_by(review_id)%>%
#                     mutate(review_sentiment = sum(sentiment))

```

\color{red} 
BE CAREFUL!!! IT TOOK ME 24 HOURS RUN THE WHOLE PROCESS!!! 
\color{black}
```{r, eval=FALSE}
tot_review <- dim(review)[1]
process_round <- ceiling(tot_review/10000)

##round 1
review1 <- review[1:10000,]
review1_sentence <- review1 %>% unnest_tokens(sentence, text, token = "sentences")
review1_element <- tibble::rowid_to_column(review1_sentence, "element_id")

review1_sentiment <- sentiment(na.omit(get_sentences(review1_element$sentence)) )
review_sentiment_score <- review1_element %>% 
                           inner_join(review1_sentiment, by = "element_id") %>%
                           group_by(review_id)%>%
                           mutate(review_sentiment = sum(sentiment))%>%
                           select(review_id, user_id,business_id, stars, date, review_sentiment)%>%
                           unique()
rm("review1","review1_sentence","review1_element","review1_sentiment")
                           
##round 2 : 600

for (i in 2:process_round) {
  
  if(i< process_round)   review_temp <- review[((i-1)*10000 +1) :(10000*i),]
  else review_temp <- review[((i-1)*10000 +1):tot_review,]
  
  review_temp_sentence <- review_temp %>% unnest_tokens(sentence, text, token = "sentences")
  review_temp_element <- tibble::rowid_to_column(review_temp_sentence, "element_id")

  review_temp_sentiment <- sentiment(na.omit(get_sentences(review_temp_element$sentence)) )
  review_temp_sentiment_score <- review_temp_element %>% 
                           inner_join(review_temp_sentiment, by = "element_id") %>%
                           group_by(review_id)%>%
                           mutate(review_sentiment = sum(sentiment))%>%
                           select(review_id, user_id,business_id, stars, date, review_sentiment)%>%
                           unique()
  print(paste("round",i,"processed successfully, with", dim(review_temp_sentiment_score)[1],"observations"))
  
  review_sentiment_score <- rbind(review_sentiment_score, review_temp_sentiment_score)
  print(paste("now sentiment dataframe has ", dim(review_sentiment_score)[1],"observations."))
  
  rm("review_temp","review_temp_sentence","review_temp_element","review_temp_sentiment",
     "review_temp_sentiment_score")

}

rm("i","tot_review","process_round")

save(review_sentiment_score, file = "dataset/review_sentiment_score.Rdata")

```

###simple benford analysis on users' review sentiment score
```{r}
bfd.review_sentiment <- benford(review_sentiment_score$review_sentiment)
plot(bfd.review_sentiment)
suspect_reviews <- getSuspects(bfd.review, review_sentiment_score)
suspect_ratio <- nrow(suspect.review)/nrow(review_sentiment_score)
print(paste("The suspect reviews account for",round(suspect_ratio*100,2), "%" ))
```


##filter all resturant data from `business_info`
###`inner_join` with sentiment score ,and filter out "restuarant" info
```{r}
restaurant_info <- business_info %>%
                   filter(str_detect(categories,"Restaurants"))
restaurant_category <- unique(unlist(str_split(restaurant_info$categories ,",")))

review_restaurant <- restaurant_info %>%
                     inner_join(review_sentiment_score, by="business_id" ) %>%
                     filter(is_open== "TRUE") %>%
                     select(-c("neighborhood","is_open"))
save(review_restaurant, file = "Dataset/review_restaurant.Rdata")
#review_restaurant$categories <- str_remove(review_restaurant$categories, c("Restaurants,","Restaurants"))

str(review_restaurant )
```




